services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - PROJECT_ROOT=/app
      - FLOODNS_ROOT=/app/floodns
    command: ["python", "main.py"]
